/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Client;
import persistence.ClientDAOImp;

/**
 *
 * @author Usuario
 */
public class ClientList extends javax.swing.JFrame {
    ArrayList<Client> listClient = new ArrayList();
    DefaultTableModel dtmClients = new DefaultTableModel();

    public ClientList() {
        initComponents();
        this.setLocationRelativeTo(null);
        setModelo();
    }

    public void setModelo() {
        String[] header = {"Id", "Full Name", "Address", "Email", "Phone", "State", "Type", "Notes"};
        dtmClients.setColumnIdentifiers(header);
        clientTbl.setModel(dtmClients);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clientModeLbl = new javax.swing.JLabel();
        clienteDataBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        clientDeleteBtn = new javax.swing.JButton();
        clientUpdateBtn = new javax.swing.JButton();
        clientCloseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Clients");

        clientModeLbl.setText("List Mode");

        clienteDataBtn.setText("Data");
        clienteDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clienteDataBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(219, 219, 219)
                            .addComponent(clientModeLbl))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientModeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clienteDataBtn)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        clientDeleteBtn.setText("Delete");
        clientDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientDeleteBtnActionPerformed(evt);
            }
        });

        clientUpdateBtn.setText("Update");

        clientCloseBtn.setText("Close");
        clientCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCloseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(clientDeleteBtn)
                .addGap(95, 95, 95)
                .addComponent(clientUpdateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clientCloseBtn)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientDeleteBtn)
                    .addComponent(clientUpdateBtn)
                    .addComponent(clientCloseBtn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        clientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        clientTbl.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(clientTbl);
        clientTbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteDataBtnActionPerformed
        ClientDAOImp clientDAOImp = new ClientDAOImp();
        //Se traen los datos de la BD
        try {
            listClient = (ArrayList<Client>) clientDAOImp.listClients();
            Object[] data = new Object[dtmClients.getColumnCount()];
            int i = 1;
            dtmClients.setRowCount(0);
            for (Client client : listClient) {
                data[0] = client.getId();
                data[1] = client.getFullName();
                data[2] = client.getAddress();
                data[3] = client.getEmail();
                data[4] = client.getPhone();
                data[5] = client.isState();
                data[6] = client.getType();
                data[7] = client.getNotes();
                i++;
                dtmClients.addRow(data);
            }
            clientTbl.setModel(dtmClients);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_clienteDataBtnActionPerformed

    private void clientCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCloseBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_clientCloseBtnActionPerformed

    private void clientDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientDeleteBtnActionPerformed
        int index = clientTbl.getSelectedRow();
        Client client = listClient.get(index);
        JOptionPane.showMessageDialog(null, client.getId());
        ClientDAOImp clientDAOImp = new ClientDAOImp();
        int rta = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?",
                "Remove Client Registry", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (rta == 0) {
            try {
                clientDAOImp.deleteClient(client);
                JOptionPane.showMessageDialog(null, "Deleted Client Record");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Operation Not Performed");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operation Not Performed");
        }
        if (dtmClients.getRowCount() > 0) {
            for (int i = dtmClients.getRowCount() - 1; i > -1; i--) {
                dtmClients.removeRow(i);
            }
            try {
                var clients = clientDAOImp.listClients();
                Object[] data = new Object[dtmClients.getColumnCount()];
                int i = 1;
                dtmClients.setRowCount(0);
                for (Client c : clients) {
                    data[0] = c.getId();
                    data[1] = c.getFullName();
                    data[2] = c.getAddress();
                    data[3] = c.getEmail();
                    data[4] = c.getPhone();
                    data[5] = c.isState();
                    data[6] = c.getType();
                    data[7] = c.getNotes();
                    i++;
                    dtmClients.addRow(data);
                }
                clientTbl.setModel(dtmClients);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_clientDeleteBtnActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientCloseBtn;
    private javax.swing.JButton clientDeleteBtn;
    private javax.swing.JLabel clientModeLbl;
    private javax.swing.JTable clientTbl;
    private javax.swing.JButton clientUpdateBtn;
    private javax.swing.JButton clienteDataBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
