
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Organization;
import javax.swing.JOptionPane;
import persistence.OrganizationDAOImp;
import java.util.Collections;
import java.util.Comparator;
           
public class OrganizationList extends javax.swing.JFrame {
    ArrayList<Organization> listOrganization = new ArrayList();
    DefaultTableModel dtmOrganizations = new DefaultTableModel();
   
    public OrganizationList() {
        initComponents();
        this.setLocationRelativeTo(null);
        setModelo();
    }

    public void setModelo() {
        String[] header = {"Id", "Legal Name", "Comercial Name", "Date Register", "Type", "State", "Notes", "Phone", "Email", "Address", "City", "Coutry", "Postal Code" };
        dtmOrganizations.setColumnIdentifiers(header);
        organizationTbl.setModel(dtmOrganizations);
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        organizationDataBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        organizationUpdateBtn = new javax.swing.JButton();
        organizationCloseBtn = new javax.swing.JButton();
        organizationDeleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Organization");

        jLabel2.setText("List Mode");

        organizationDataBtn.setText("Data");
        organizationDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(organizationDataBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organizationDataBtn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        organizationTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(organizationTbl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        organizationUpdateBtn.setText("Update");

        organizationCloseBtn.setText("Close");
        organizationCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationCloseBtnActionPerformed(evt);
            }
        });

        organizationDeleteBtn.setText("Delete");
        organizationDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(organizationDeleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(organizationUpdateBtn)
                .addGap(61, 61, 61)
                .addComponent(organizationCloseBtn)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationUpdateBtn)
                    .addComponent(organizationCloseBtn)
                    .addComponent(organizationDeleteBtn))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void organizationCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationCloseBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_organizationCloseBtnActionPerformed

    private void organizationDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationDataBtnActionPerformed
        OrganizationDAOImp organizationDAOImp = new OrganizationDAOImp();
        //Se traen los datos de la BD
        try {
            listOrganization = (ArrayList<Organization>) organizationDAOImp.listOrganization();
            Object[] data = new Object[dtmOrganizations.getColumnCount()];
            int i = 1;
            dtmOrganizations.setRowCount(0);
            for (Organization organization : listOrganization) {
                data[0] = organization.getId();
                data[1] = organization.getlegalName();
                data[2] = organization.getcomercialName();
                data[3] = organization.getdateRegister();
                data[4] = organization.gettype();
                data[5] = organization.isstate();
                data[6] = organization.getnotes();
                data[7] = organization.getphone();
                data[8] = organization.getemail();
                data[9] = organization.getaddress();
                data[10] = organization.getcity();
                data[11] = organization.getcoutry();
                data[12] = organization.getpostalCode();
                i++;
                dtmOrganizations.addRow(data);
            }

            organizationTbl.setModel(dtmOrganizations);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_organizationDataBtnActionPerformed

    private void organizationDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationDeleteBtnActionPerformed
        int index = organizationTbl.getSelectedRow();
        Organization organization = listOrganization.get(index);
        //JOptionPane.showMessageDialog(null, organization.getId());
        OrganizationDAOImp organizationDAOImp = new OrganizationDAOImp();
        int rta = JOptionPane.showConfirmDialog(null, "Do you want to delete the record?",
                "Remove Organization Registry", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (rta == 0) {
            try {
                organizationDAOImp.deleteOrganization(organization);
                JOptionPane.showMessageDialog(null, "Deleted Organization Record");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Operation Not Performed");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operation Not Performed");
        }
        if (dtmOrganizations.getRowCount() > 0) {
            for (int i = dtmOrganizations.getRowCount() - 1; i > -1; i--) {
                dtmOrganizations.removeRow(i);
            }
            try {
                var organizations = organizationDAOImp.listOrganization();
                Object[] data = new Object[dtmOrganizations.getColumnCount()];
                int i = 1;
                dtmOrganizations.setRowCount(0);
                for (Organization c : organizations) {
                    data[0] = c.getId();
                    data[1] = c.getlegalName();
                    data[2] = c.getcomercialName();
                    data[3] = c.getdateRegister();
                    data[4] = c.gettype();
                    data[5] = c.isstate();
                    data[6] = c.getnotes();
                    data[7] = c.getphone();
                    data[8] = c.getemail();
                    data[9] = c.getaddress();
                    data[10] = c.getcity();
                    data[11] = c.getcoutry();
                    data[12] = c.getpostalCode();
                    i++;
                    dtmOrganizations.addRow(data);
                }
                organizationTbl.setModel(dtmOrganizations);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
                                                   

    
    }//GEN-LAST:event_organizationDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganizationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganizationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganizationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganizationList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizationList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton organizationCloseBtn;
    private javax.swing.JButton organizationDataBtn;
    private javax.swing.JButton organizationDeleteBtn;
    private javax.swing.JTable organizationTbl;
    private javax.swing.JButton organizationUpdateBtn;
    // End of variables declaration//GEN-END:variables
}
